name: a2c

agent_name: ${now:%Y%m%d}_sac_gnn  # Agent name for training or evaluation (default: today's date + '_sac_gnn')

cplexpath: "None"  # Defines directory of the CPLEX installation

directory: "saved_files"  # Defines directory where to save files

max_episodes: 5000  # Number of episodes to train agent (default: 16k)

max_steps: 150  # Number of steps per episode (default: T=120)

no_cuda: false  # Disables CUDA training

batch_size: 100  # Defines batch size

p_lr: 1e-2  # Define policy learning rate (default: 1e-3)

q_lr: 1e-2  # Defines q-value learning rate (default: 1e-3)

hidden_size: 256  # Defines hidden units in the MLP layers

clip: 500  # Clip value for gradient clipping (default: 500)

checkpoint_path: "A2C"  # Path where to save model checkpoints

load_from_ckeckpoint: false  # Load model from checkpoint

input_size: 3 # Number of node features

test_episodes: 10 # Number of episodes to test agent

wandb: false # Enables Weights and Biases logging

tensorboard: true # Log via tensorboard enabled