name: td3

agent_name: ${now:%Y%m%d}_td3_gnn  # Agent name for training or evaluation (default: today's date + '_sac_gnn')

cplexpath: "None"  # Defines directory of the CPLEX installation

directory: "saved_files"  # Defines directory where to save files

max_episodes: 10000  # Number of episodes to train agent (default: 16k)

no_cuda: false  # Disables CUDA training

batch_size: 100  # Defines batch size

checkpoint_path: "TD3"  # Path where to save model checkpoints

load_from_ckeckpoint: false  # Load model from checkpoint

hidden_size: 256  # Defines hidden units in the MLP layers

input_size: 3 # Number of node features

test_episodes: 10 # Number of episodes to test agent

mask_impactless_actions: true # Mask useless actions

tensorboard: true # Enables Tensorboard logging

wandb: false # Enables Weights and Biases logging